import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { Flip, ToastContainer } from "react-toastify";
import { AuthProvider } from "@/context/authContext";
import { CartProvider } from "@/context/cartContext";
import RoutesPrivacy from "@/hook/useRoutesPrivacy/routes-privacy";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The Crafted Home",
  description: "Generated by The Crafted Home",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <CartProvider>
            <RoutesPrivacy>{children}</RoutesPrivacy>
          </CartProvider>
        </AuthProvider>

        <ToastContainer
          position="top-center"
          autoClose={2500}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss={false}
          draggable={false}
          pauseOnHover={false}
          theme="light"
          transition={Flip}
        />
      </body>
    </html>
  );
}
